var chart = AmCharts.makeChart("chartdiv", {
    "theme": "none",
    "type": "serial",
    "hideCredits":true,
    "dataProvider": [{
        "exp": "Partidos políticos",
        "muy": 46.5,
        "muy_dos": 53.1,
        "muy_tres": 58.5,
        "frecuente": 38.3,
        "frecuente_dos": 34.6,
        "frecuente_dos": 27.9,
        "poco": 10.6,
        "poco_dos": 7.4,
        "poco_tres": 8.2,
        "nada": 2.7,
        "nada_dos": 1.6,
        "nada_tres": 2.4,
        "nosabe": 1.9,
        "nosabe_dos": 3.3,
        "nosabe_tres": 3.0,
        "label": 0,
        "label_dos": 0,
        "label_tres": 0
    },
    {
        "exp": "Policías",
        "muy": 51.6,
        "muy_dos": 48.9,
        "muy_tres": 50.0,
        "frecuente": 29.7,
        "frecuente_dos": 35.2,
        "frecuente_dos": 31.5,
        "poco": 15.6,
        "poco_dos": 11.1,
        "poco_tres": 15.4,
        "nada": 1.4,
        "nada_dos": 1.8,
        "nada_tres": 1.7,
        "nosabe": 1.6,
        "nosabe_dos": 2.9,
        "nosabe_tres": 1.4,
        "label": 0,
        "label_dos": 0,
        "label_tres": 0
    },
    {
        "exp": "Diputados y Senadores",
        "muy": 35.2,
        "muy_dos": 40.8,
        "muy_tres": 51.9,
        "frecuente": 37.5,
        "frecuente_dos": 34.3,
        "frecuente_dos": 25.6,
        "poco": 16.1,
        "poco_dos": 11.0,
        "poco_tres": 11.7,
        "nada": 2.4,
        "nada_dos": 3.5,
        "nada_tres": 3.1,
        "nosabe": 8.8,
        "nosabe_dos": 10.4,
        "nosabe_tres": 7.6,
        "label": 0,
        "label_dos": 0,
        "label_tres": 0
    },
    {
        "exp": "Gobierno Federal",
        "muy": 36.1,
        "muy_dos": 48.8,
        "muy_tres": 52.0,
        "frecuente": 34.9,
        "frecuente_dos": 28.9,
        "frecuente_dos": 28.9,
        "poco": 20.7,
        "poco_dos": 8.9,
        "poco_tres": 11.5,
        "nada": 3.3,
        "nada_dos": 3.2,
        "nada_tres": 3.0,
        "nosabe": 5.0,
        "nosabe_dos": 10.2,
        "nosabe_tres": 4.7,
        "label": 0,
        "label_dos": 0,
        "label_tres": 0
    },
    {
        "exp": "Gobiernos Municipales",
        "muy": 26.9,
        "muy_dos": 32.0,
        "muy_tres": 29.5,
        "frecuente": 39.5,
        "frecuente_dos": 38.2,
        "frecuente_dos": 36.6,
        "poco": 22.9,
        "poco_dos": 19.8,
        "poco_tres": 23.4,
        "nada": 4.6,
        "nada_dos": 3.3,
        "nada_tres": 5.1,
        "nosabe": 6.0,
        "nosabe_dos": 6.7,
        "nosabe_tres": 5.4,
        "label": 0,
        "label_dos": 0,
        "label_tres": 0
    },
    {
        "exp": "Gobiernos Estatales",
        "muy": 26.7,
        "muy_dos": 27.3,
        "muy_tres": 32.5,
        "frecuente": 38.8,
        "frecuente_dos": 35.4,
        "frecuente_dos": 35.7,
        "poco": 24.1,
        "poco_dos": 22.2,
        "poco_tres": 23.1,
        "nada": 4.8,
        "nada_dos": 7.6,
        "nada_tres": 4.0,
        "nosabe": 5.6,
        "nosabe_dos": 7.5,
        "nosabe_tres": 4.7,
        "label": 0,
        "label_dos": 0,
        "label_tres": 0
    }],
    "valueAxes": [{
        "stackType": "regular",
        "position": "left",
        "title": ""
    }],
    "startDuration": 1,    
    "graphs": [
     // 1200 stack
     {
        "fillAlphas": 0,
        "lineAlpha": 0,
        "title": "2013",
        "type": "column",
        "valueField": "label",
         "showAllValueLabels": true,
         "labelText": "\n[[title]]"
     },
     {
        "fillAlphas": 1,        
        "lineAlpha": 0.2,
        "fillColors": "#4D8691",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2013",

        "type": "column",
        "valueField": "muy"
    }, {
        "fillAlphas": 1,        
        "lineAlpha": 0.2,
        "fillColors": "#5597A3",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2013",
        "type": "column",
        "valueField": "frecuente"
    }, {
        "fillAlphas": 1,        
        "lineAlpha": 0.2,
        "fillColors": "#64A3AF",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2013",
        "type": "column",
        "valueField": "poco"
    }, {
        "fillAlphas": 1,        
        "lineAlpha": 0.2,
        "fillColors": "#74AEB8",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2013",
        "type": "column",
        "valueField": "nada"
    }, {
        "fillAlphas": 1,        
        "lineAlpha": 0.2,
        "fillColors": "#85B8C2",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2013",
        "type": "column",
        "valueField": "nosabe"
    },
    // 0100 stack
    {
        "newStack": true,
        "fillAlphas": 0,
        "lineAlpha": 0,
        "title": "2015",
        "type": "column",
        "valueField": "label_dos",
         "showAllValueLabels": true,
         "labelText": "\n[[title]]"
     },
    {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#4D8691",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2015",
        "type": "column",
        "valueField": "muy_dos"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#5597A3",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2015",
        "type": "column",
        "valueField": "frecuente_dos"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#64A3AF",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2015",
        "type": "column",
        "valueField": "poco_dos"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#74AEB8",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2015",
        "type": "column",
        "valueField": "nada_dos"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#85B8C2",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2015",
        "type": "column",
        "valueField": "nosabe_dos"
    },
    // 0200 stack
    {
        "newStack": true,
        "fillAlphas": 0,
        "lineAlpha": 0,
        "title": "2017",
        "type": "column",
        "valueField": "label",
         "showAllValueLabels": true,
         "labelText": "\n[[title]]"
     },
    {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#4D8691",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2017",
        "type": "column",
        "valueField": "muy_tres"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#5597A3",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2017",
        "type": "column",
        "valueField": "frecuente_dos"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#64A3AF",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2017",
        "type": "column",
        "valueField": "poco_tres"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#74AEB8",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2017",
        "type": "column",
        "valueField": "nada_tres"
    }, {
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "fillColors": "#85B8C2",
        "labelText": "[[value]]",
        "color": "#fff",
        "title": "2017",
        "type": "column",
        "valueField": "nosabe_tres"
    }    
    ],
    "plotAreaFillAlphas": 0.1,
    "depth3D": 0,
    "angle": 0,
    "categoryField": "exp",
    "categoryAxis": {
        "labelOffset": 15,
        "gridPosition": "start",
        "tickPosition": "start"
    }
});